Repository scikit-hep/particle, pull requests merged in 2022-11, with the labels that each got.

#433 Add PDG 2022 particle data table file
  src/particle/data/mass_width_2022.mcd
Labels: data files

#435 chore: Prepare release 0.21.0
  docs/CHANGELOG.md
Labels: release

#437 ci: fix warnings
  .github/workflows/cd.yml
  noxfile.py
Labels: CI
