Repository scikit-hep/particle, pull requests merged in 2024-09, with the labels that each got.

#621 Add internal quantum numbers for several mesons
  src/particle/data/mass_width_2008_ext.fwf
  src/particle/data/particle2024.csv
Labels: ⚙️ enhancement

#623 add pre-commit to dev-deps, add all extra
  pyproject.toml
Labels: CI

#622 Make sure neutron, proton and their anti-particles compare equal
  src/particle/particle/particle.py
  tests/particle/test_particle.py
Labels: ⚙️ enhancement, bug fix

#630 ci: faster with uv
  .github/workflows/ci.yml
  noxfile.py
  pyproject.toml
  src/particle/_compat/typing.py
Labels: CI

#631 ci: add attestations
  .github/workflows/cd.yml
Labels: CI
