Repository scikit-hep/particle, pull requests merged in 2024-04, with the labels that each got.

#581 chore: require Python 3.8+
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
  environment.yml
  noxfile.py
  pyproject.toml
  src/particle/_compat/typing.py
  src/particle/typing.py
  tests/test_module_apis.py
Labels: dependencies

#583 chore: add pixi support
  .gitignore
  environment.yml
  notebooks/ParticleDemo.ipynb
  pyproject.toml
Labels: ⚙️ enhancement

#588 FIX: fix Lambda(1405) LaTeX typo
  src/particle/data/conversions.csv
  src/particle/data/particle2021.csv
  src/particle/data/particle2022.csv
  src/particle/data/particle2023.csv
  src/particle/data/pdgid_to_latexname.csv
Labels: bug fix

#590 Prepare for release 0.24.0
  docs/CHANGELOG.md
Labels: release

#592 ci: macos-latest is changing to macos-14 ARM runners
  .github/workflows/ci.yml
Labels: CI
