Repository scikit-hep/particle, pull requests merged in 2025-05, with the labels that each got.

#673 fix: higgs j_spin is zero
  src/particle/pdgid/functions.py
Labels: bug fix

#675 Fix the creation of programmatic names for nuclei when the nucleus names end with a 0
  src/particle/particle/particle.py
  src/particle/particle/utilities.py
  tests/particle/test_utilities.py
Labels: bug fix

#677 Improve helper PDGID related _digit function
  src/particle/pdgid/functions.py
Labels: ⚙️ enhancement

#680 Prepare release 0.25.4
  docs/CHANGELOG.md
Labels: release
